- name: Enable WinRM
  ansible.windows.win_powershell:
    script: |
      Set-Service -Name WinRM -StartupType Automatic
      if ((Get-Service WinRM).Status -ne 'Running') {
          Start-Service WinRM
      }

- name: Add NETWORK SERVICE to Event Log Readers
  ansible.windows.win_command:
    cmd: net localgroup "Event Log Readers" "NETWORK SERVICE" /add
  failed_when: false
